"""memex — a typed, immutable, provenance-tracked memory graph for AI agents.

Pydantic port of ``@ai2070/memex``. Public surface grows phase by phase; this
barrel re-exports everything implemented so far.
"""

from __future__ import annotations

from ._uuid import safe_extract_timestamp, uuid7
from .bulk import (
    ItemTransform,
    ScoreAdjustment,
    apply_many,
    bulk_adjust_scores,
    decay_importance,
)
from .commands import (
    EdgeCreate,
    EdgeRetract,
    EdgeUpdate,
    MemoryCommand,
    MemoryCommandAdapter,
    MemoryCreate,
    MemoryRetract,
    MemoryUpdate,
)
from .envelope import wrap_edge_state_event, wrap_lifecycle_event, wrap_state_event
from .errors import (
    DuplicateEdgeError,
    DuplicateMemoryError,
    EdgeNotFoundError,
    InvalidTimestampError,
    MemexError,
    MemoryNotFoundError,
)
from .factories import create_edge, create_event_envelope, create_memory_item
from .graph import GraphState, clone_graph_state, create_graph_state
from .integrity import (
    CascadeResult,
    Contradiction,
    StaleItem,
    cascade_retract,
    get_alias_group,
    get_aliases,
    get_contradictions,
    get_dependents,
    get_items_by_budget,
    get_stale_items,
    mark_alias,
    mark_contradiction,
    resolve_contradiction,
)
from .intent import (
    DuplicateIntentError,
    Intent,
    IntentCommand,
    IntentFilter,
    IntentLifecycleEvent,
    IntentNotFoundError,
    IntentResult,
    IntentState,
    IntentStatus,
    InvalidIntentTransitionError,
    apply_intent_command,
    create_intent,
    create_intent_state,
    get_child_intents,
    get_intent_by_id,
    get_intents,
)
from .models import (
    CreatedFilter,
    DecayConfig,
    DecayFilter,
    DecayInterval,
    DecayType,
    Edge,
    EdgeFilter,
    EventEnvelope,
    KnownEdgeKind,
    KnownMemoryKind,
    KnownNamespace,
    KnownSourceKind,
    LifecycleEventType,
    MemoryFilter,
    MemoryItem,
    MemoryLifecycleEvent,
    ParentsFilter,
    QueryOptions,
    Range,
    ScoredItem,
    ScoreRanges,
    ScoreWeights,
    SortField,
    SortOption,
)
from .query import (
    ScoredQueryOptions,
    compute_decay_multiplier,
    compute_score,
    extract_timestamp,
    get_children,
    get_edge_by_id,
    get_edges,
    get_item_by_id,
    get_items,
    get_parents,
    get_related_items,
    get_scored_items,
    matches_filter,
)
from .reducer import CommandResult, apply_command, merge_edge, merge_item
from .replay import (
    ReplayFailure,
    ReplayResult,
    replay_commands,
    replay_from_envelopes,
)
from .retrieval import (
    DiversityOptions,
    SupportNode,
    apply_diversity,
    filter_contradictions,
    get_support_set,
    get_support_tree,
    smart_retrieve,
    surface_contradictions,
)
from .serialization import (
    SerializedGraphState,
    from_json,
    parse,
    stringify,
    to_json,
)
from .stats import EdgeStats, GraphStats, ItemStats, get_stats
from .store import MemexStore
from .task import (
    DuplicateTaskError,
    InvalidTaskTransitionError,
    Task,
    TaskCommand,
    TaskFilter,
    TaskLifecycleEvent,
    TaskNotFoundError,
    TaskResult,
    TaskState,
    TaskStatus,
    apply_task_command,
    create_task,
    create_task_state,
    get_child_tasks,
    get_task_by_id,
    get_tasks,
    get_tasks_by_intent,
)
from .transplant import (
    ExportOptions,
    ImportBucket,
    ImportOptions,
    ImportReport,
    ImportResult,
    MemexExport,
    export_slice,
    import_slice,
)

__all__ = [
    # uuid
    "uuid7",
    "safe_extract_timestamp",
    # graph state
    "GraphState",
    "create_graph_state",
    "clone_graph_state",
    # reducer
    "apply_command",
    "CommandResult",
    "merge_item",
    "merge_edge",
    # query
    "get_items",
    "get_scored_items",
    "get_edges",
    "get_item_by_id",
    "get_edge_by_id",
    "get_related_items",
    "get_parents",
    "get_children",
    "matches_filter",
    "compute_score",
    "compute_decay_multiplier",
    "extract_timestamp",
    "ScoredQueryOptions",
    # retrieval
    "get_support_tree",
    "get_support_set",
    "filter_contradictions",
    "surface_contradictions",
    "apply_diversity",
    "smart_retrieve",
    "SupportNode",
    "DiversityOptions",
    # integrity
    "get_contradictions",
    "mark_contradiction",
    "resolve_contradiction",
    "get_stale_items",
    "get_dependents",
    "cascade_retract",
    "mark_alias",
    "get_aliases",
    "get_alias_group",
    "get_items_by_budget",
    "Contradiction",
    "StaleItem",
    "CascadeResult",
    # bulk
    "apply_many",
    "bulk_adjust_scores",
    "decay_importance",
    "ScoreAdjustment",
    "ItemTransform",
    # replay
    "replay_commands",
    "replay_from_envelopes",
    "ReplayFailure",
    "ReplayResult",
    # envelope
    "wrap_lifecycle_event",
    "wrap_state_event",
    "wrap_edge_state_event",
    # serialization
    "to_json",
    "from_json",
    "stringify",
    "parse",
    "SerializedGraphState",
    # stats
    "get_stats",
    "GraphStats",
    "ItemStats",
    "EdgeStats",
    # intent graph
    "create_intent_state",
    "create_intent",
    "apply_intent_command",
    "get_intents",
    "get_intent_by_id",
    "get_child_intents",
    "Intent",
    "IntentState",
    "IntentStatus",
    "IntentCommand",
    "IntentFilter",
    "IntentLifecycleEvent",
    "IntentResult",
    "IntentNotFoundError",
    "DuplicateIntentError",
    "InvalidIntentTransitionError",
    # task graph
    "create_task_state",
    "create_task",
    "apply_task_command",
    "get_tasks",
    "get_task_by_id",
    "get_tasks_by_intent",
    "get_child_tasks",
    "Task",
    "TaskState",
    "TaskStatus",
    "TaskCommand",
    "TaskFilter",
    "TaskLifecycleEvent",
    "TaskResult",
    "TaskNotFoundError",
    "DuplicateTaskError",
    "InvalidTaskTransitionError",
    # transplant
    "export_slice",
    "import_slice",
    "MemexExport",
    "ExportOptions",
    "ImportOptions",
    "ImportReport",
    "ImportBucket",
    "ImportResult",
    # facade
    "MemexStore",
    # factories
    "create_memory_item",
    "create_edge",
    "create_event_envelope",
    # models
    "MemoryItem",
    "Edge",
    "EventEnvelope",
    "DecayConfig",
    "ScoreWeights",
    "ScoredItem",
    "MemoryFilter",
    "EdgeFilter",
    "SortOption",
    "QueryOptions",
    "Range",
    "ScoreRanges",
    "ParentsFilter",
    "DecayFilter",
    "CreatedFilter",
    "MemoryLifecycleEvent",
    # type aliases
    "KnownMemoryKind",
    "KnownSourceKind",
    "KnownEdgeKind",
    "KnownNamespace",
    "LifecycleEventType",
    "SortField",
    "DecayInterval",
    "DecayType",
    # commands
    "MemoryCommand",
    "MemoryCommandAdapter",
    "MemoryCreate",
    "MemoryUpdate",
    "MemoryRetract",
    "EdgeCreate",
    "EdgeUpdate",
    "EdgeRetract",
    # errors
    "MemexError",
    "MemoryNotFoundError",
    "EdgeNotFoundError",
    "DuplicateMemoryError",
    "DuplicateEdgeError",
    "InvalidTimestampError",
]
